### ISSUE TITLE
react-step-4 tutorial issues

### ISSUE THREAD

**Issue by JuliusKoronci** [carbon-design-system/carbon-website#2889] opened 2022-04-15 18:38 UTC
## Detailed description
I will give a few examples here:

```
.info-card__heading {
  @include type-style('productive-heading-03');
}
```
raises an error when running, needs to be corrected to 
```
.info-card__heading {
  @include carbon--type-style('productive-heading-03');
}
```

another one for the html
```
cds--col-md-4
```
needs to be corrected to
```
bx--col-md-4
```

The same issues are in the entire tutorial, I did raise one PR but I have some CI failure I dunno how to solve so for the rest I am raising just bugs :)

**Comment by tay1orjones** [comment] 2022-04-21 20:52
@JuliusKoronci Thanks for reporting this! We're working to update the tutorial right now and tracking it in https://github.com/carbon-design-system/carbon/issues/10991.

Will close this in favor of that one, we'll include this as part of that update. Thank you again!

**Comment by tay1orjones** [comment] 2022-04-21 20:52
Duplicate of https://github.com/carbon-design-system/carbon/issues/10991

**Closed by tay1orjones** 2022-04-21 20:52 UTC
Labels: type: bug 🐛
