### ISSUE TITLE
bug[homepage cards]: Getting started cards are out of alignment / off grid

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1258] opened 2019-03-04 20:00 UTC
These cards should be flush with the right edge of the graphic like they used to be, they are correct in Safari but off alignment in Chrome and Firefox.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/483104fd-469e-4bbb-be92-6d0554b8681f)

**Comment by alisonjoseph** [comment] 2019-03-05 16:31
this is a duplicate of #1252

**Closed** 2019-03-22 14:17 UTC
Labels: QA :male_detective:, project: website, type: bug 🐛, type: dev :robot:, v10 :new:
