### ISSUE TITLE
Data Table Page Select Issue

### ISSUE THREAD

**Issue by skcele** [carbon-design-system/carbon-website#652] opened 2019-12-06 18:03 UTC
## Detailed description

> On the Data Table code page, I selected and unselected rows in the Expandable Data Table Example, and then unselected the focus on the table.

> I then tried to select a row in the Data Table with Pagination (the next sample beneath it) and it selected rows from the previous table (Expandable Data Table) instead.

> I am working in Chrome.

## Steps to reproduce the issue

1. Go to [the data table page](https://www.carbondesignsystem.com/components/data-table/code/)
2. Select and unselect rows in Expandable Data Table. Click outside table to remove focus.
3. Select a row in Data Table with Pagination.

## Additional information

![Kapture 2019-12-06 at 12 01 44](https://user-images.githubusercontent.com/16628960/70344929-70e07600-1820-11ea-95f1-d3fed0d3db35.gif)

**Comment by xxxle0** [comment] 2020-01-15 17:08
this bug caused by duplicated label id in the same page. We can fix that by change the label_id in data-table--expandable.html in carbon-components. @vpicone Do you know how we can generate carbon-components like this ? 
![Screen Shot 2020-01-16 at 12 07 44 AM](https://user-images.githubusercontent.com/18297839/72454844-3d681280-37f4-11ea-85ee-c43191432081.png)

**Comment by jnm2377** [comment] 2020-01-16 22:39
@xxxle you are correct about the id's. The generated html is created through our hbs and config file in the actual `/carbon` repo. By changing the config file and hbs file, that will update the generated html. 

https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/data-table/data-table.hbs

https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/data-table/data-table.config.js

**Comment by xxxle0** [comment] 2020-01-17 07:08
hi @jnm2377, i created a PR for for this issue. We can close this issue after my PR merged.

**Comment by xxxle0** [comment] 2020-01-18 02:37
This issue can be closed.

**Closed** 2020-01-20 17:21 UTC
Labels: role: dev 🤖, type: bug 🐛, type: docs 📖
