### ISSUE TITLE
Carbon icon causes screen to turn black

### ISSUE THREAD

**Issue by JoshuaHorowitz** [carbon-design-system/carbon-website#2455] opened 2021-07-21 18:22 UTC
When looking up the "warning" or "warn" icon  in the library @ https://www.carbondesignsystem.com/guidelines/icons/library (and I'm sure this is true with other icons), the screen goes totally black and is not interactable.

The error is as such: 
```
framework-97f2f2b8b1af8f873102.js:1 Error: Cannot find module './caution/32'
    at Function.i [as resolve] (component---src-pages-guidelines-icons-library-js-ecf0eb5a3fcd95e89179.js:1)
    at Object.resolve (component---src-pages-guidelines-icons-library-js-ecf0eb5a3fcd95e89179.js:1)
    at f (ff4cdcd0b9254eccd3b33455573174482364e5d8-1d32dbda13dd7f98bd39.js:1)
    at new a (ff4cdcd0b9254eccd3b33455573174482364e5d8-1d32dbda13dd7f98bd39.js:1)
    at ha (framework-97f2f2b8b1af8f873102.js:1)
    at Vo (framework-97f2f2b8b1af8f873102.js:1)
    at Bu (framework-97f2f2b8b1af8f873102.js:1)
    at Ei (framework-97f2f2b8b1af8f873102.js:1)
    at ki (framework-97f2f2b8b1af8f873102.js:1)
    at wi (framework-97f2f2b8b1af8f873102.js:1)
au @ framework-97f2f2b8b1af8f873102.js:1
framework-97f2f2b8b1af8f873102.js:1 Uncaught Error: Cannot find module './caution/32'
    at Function.i [as resolve] (component---src-pages-guidelines-icons-library-js-ecf0eb5a3fcd95e89179.js:1)
    at Object.resolve (component---src-pages-guidelines-icons-library-js-ecf0eb5a3fcd95e89179.js:1)
    at f (ff4cdcd0b9254eccd3b33455573174482364e5d8-1d32dbda13dd7f98bd39.js:1)
    at new a (ff4cdcd0b9254eccd3b33455573174482364e5d8-1d32dbda13dd7f98bd39.js:1)
    at ha (framework-97f2f2b8b1af8f873102.js:1)
    at Vo (framework-97f2f2b8b1af8f873102.js:1)
    at Bu (framework-97f2f2b8b1af8f873102.js:1)
    at Ei (framework-97f2f2b8b1af8f873102.js:1)
    at ki (framework-97f2f2b8b1af8f873102.js:1)
    at wi (framework-97f2f2b8b1af8f873102.js:1)
```

**Comment by tw15egan** [comment] 2021-07-21 20:15
Thanks for reporting, going to close as a dupe of https://github.com/carbon-design-system/carbon-website/issues/2448 and you can track progress there

**Closed by tw15egan** 2021-07-21 20:15 UTC
