### ISSUE TITLE
Tags broken: Data visualization > Chart types

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1294] opened 2020-06-12 19:42 UTC
https://www.carbondesignsystem.com/data-visualization/chart-types

———————

<img width="976" alt="Screen Shot 2020-06-12 at 2 39 12 PM" src="https://user-images.githubusercontent.com/32881239/84540398-d7a48780-acba-11ea-8a88-191e89f4c002.png">

———————

<img width="962" alt="Screen Shot 2020-06-12 at 2 41 57 PM" src="https://user-images.githubusercontent.com/32881239/84540427-eb4fee00-acba-11ea-9e77-a9f96f4ae834.png">

**Comment by mjabbink** [comment] 2020-06-15 22:30
@jeanservaas

**Comment by theiliad** [comment] 2020-06-16 17:58
this was working before, and I didn't code it to begin with, nor did I change something within that component. Not sure why I was assigned

**Comment by joshblack** [comment] 2020-06-17 23:20
This seems like a regression due to this PR: https://github.com/carbon-design-system/carbon/pull/5971

**Comment by theiliad** [comment] 2020-06-17 23:28
I pushed a max height fix in my codesandbox PR, not the best fix but since
I had no context I just tried to make it work. Feel free to push your own
fix

**Comment by theiliad** [comment] 2020-06-17 23:29
Just saw you’ve pushed a fix, great thanks

**Closed** 2020-06-22 19:37 UTC
Labels: impact: high 😱, role: dev 🤖, type: bug 🐛
