### ISSUE TITLE
Button padding

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#201] opened 2019-08-28 22:32 UTC
## Detailed description

https://www.carbondesignsystem.com/components/button/style/#structure defines the left and right padding as 16px and 64px but 16px and 16px for `ghost` type.  The 64px part seems odd.  However, checking the code examples on https://www.carbondesignsystem.com/components/button/code/ have a left padding of just 15px and examples with icons have right padding of 19px.

This stems from the left-padding actually being 12px with a 3px border and the right padding being a 16px right position inside of a 3px border.

Also worth noting, the right padding is actually 60px with the 3px border making it 63px total (applied to the text, not the icon).
So the table referencing 64px makes more sense but there is still an inconsistency for `ghost` style and maybe room to clarify right padding for icon vs no icon.

## Side Note

The table lists the padding for `ghost` as `16 / 2` where the first number is `px` and the second is `rem` but 16px is actually 1rem, not 2.

Well, Tertiary style buttons get a little more interesting since they are intended to have a 1px border vs the 3px defined on primary (that blends with the background).  The left padding on a tertiary style button remains 12px so the total visual padding is just 13px from outside of button to the text.

## Additional information

![carbon_button1](https://user-images.githubusercontent.com/9935157/63897124-b8ea3400-c9b9-11e9-9514-057236f3a310.png)
![carbon_button2](https://user-images.githubusercontent.com/9935157/63897133-bdaee800-c9b9-11e9-9bfb-234377b67461.png)

**Comment by aagonzales** [comment] 2020-03-16 22:41
- Ghost button intentionally has a different padding-right than the other buttons
- 64px padding right is the correct intended padding-right is a stylistic decision made by IBM Brand. 

**Confirmed bugs to be fixed:**
- [ ] The complied padding size does not equal `64px` padding right and `16px`. I believe this may be because we reduced the width of the focus at one point and the subtracted pixel was not added back into the button size. 
![image.png](https://images.zenhubusercontent.com/5bb3952995c5721e7c272998/34de23aa-26f0-440b-830e-de6b65fe6979)
- [ ]The icon is appearing at `19px` from the edge and should be `16px`

**Comment by aagonzales** [comment] 2020-07-13 19:56
Closing since this documentation is correct (this is the website repo) but it is still incorrect in code and I have made a new issue for it in the correct repo.

https://github.com/carbon-design-system/carbon/issues/6454


We have added some clarity around padding when using [buttons with icons](https://www.carbondesignsystem.com/components/button/style#structure).

**Closed by aagonzales** 2020-07-13 19:56 UTC
Labels: role: dev 🤖, type: bug 🐛
