### ISSUE TITLE
Component Page: IA / content organization improvements

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#407] opened 2018-11-16 20:43 UTC
Review and propose a new architecture for the content of each component's guidance.

- [ ] Consider possible options for making dev vs. design guidance more clear.
- [ ] Use a more user-focused approach.
- [ ] Consider in-page indexing options.
- [ ] Establish improved standard information scheme for each component in the system.
- [ ] Explore alternate approaches to the current 3-tab architecture

How can we approach this from a jobs-to-be-done perspective?
How can we validate the new architecture via user testing?

Deliverable: standard template for a component, including tab architecture

Primary personas: product designer, product FED

**Comment by shixiedesign** [comment] 2019-02-07 05:19
closing because duplicate of #266

**Comment by claycrenshaw** [comment] 2019-02-15 20:24
Primary use cases:

**Design with Carbon**
What exactly are we building?
Which components do I use?
How should those components behave?
How do they work with other components?
What are my options for styling them?

**Code with Carbon**
How do we build it?
What is the source JS?
What is configurable in code?
How do I configure this component?
What other things do I need to know while coding a UI with this component?

**Comment by claycrenshaw** [comment] 2019-02-18 15:44
Here's some user feedback on this issue: #1850

**Comment by aagonzales** [comment] 2019-02-18 18:01
Related issue: https://github.com/carbon-design-system/carbon-website/issues/266

**Comment by claycrenshaw** [comment] 2019-02-18 21:21
Consolidating with a similar issue (266):

from Tyler:

As a product designer I can discover the usage and behavior guidance for a component so I can reference as I design and validate design decisions with developers.

* Improve discoverability of Usage.
* Add more usage and behavior guidance. "Usage is information that I can't get from the design kit"
* Consider how the content will be shared between designer and developer. Anchor links, discoverability, clarity,  "Once we used (Carbon site) to check/validate in a meeting" "If we're fighting on stuff about something, I'll copy and paste code, or show them the React storybook."

**Comment by claycrenshaw** [comment] 2019-02-18 21:23
from Shixie:

https://github.com/carbon-design-system/carbon-website/issues/266#issuecomment-461291534

**Comment by claycrenshaw** [comment] 2019-02-25 17:32
v1 Sketch file: https://ibm.box.com/s/h73ifbv67z04oyzbcylj3jqdqelm8hd5

**Closed** 2019-04-27 17:38 UTC
Labels: project: website, type: enhancement 💡, type: ux :popcorn:, wontfix
