### ISSUE TITLE
[Carbon X] ProgressIndicator does not render correctly on the website

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon-website#1032] opened 2019-02-08 21:58 UTC
## Detailed description

Hey there, the `ProgressIndicator` component is not rendering correctly on the Carbon X website: https://next.carbondesignsystem.com/components/progress-indicator/code/

<img width="1187" alt="screen shot 2019-02-08 at 3 50 57 pm" src="https://user-images.githubusercontent.com/9057921/52508438-53b82800-2bba-11e9-858f-89b31a315201.png">

I saw this in both Firefox 65 & Chrome 71.

**Comment by asudoh** [comment] 2019-02-09 10:14
Hi @jendowns thank you for reporting! Seems that [below style](https://github.com/carbon-design-system/carbon-website/pull/389/files#diff-1716f6d8f4d743f483539a63cfb724f7R9) overrides one of `.bx--progress-label`:

```css
.component-example p {
  margin: 0;
}
```

CC @alisonjoseph @jnm2377

**Comment by emyarod** [comment] 2019-02-09 17:53
```css
.page-content p {
  padding: 0 0 1.5rem;
}
```

is also affecting the bottom border of the progress labels

![image](https://user-images.githubusercontent.com/8265238/52524312-4013cc80-2c61-11e9-91fc-7eac41e5fedc.png)

**Comment by jnm2377** [comment] 2019-02-09 21:14
This is a duplicate of #1002.

**Comment by jnm2377** [comment] 2019-02-09 21:15
Looks like this is a duplicate of #1004

**Comment by asudoh** [comment] 2019-02-09 22:44
@jnm2377 Just saw this, the issue you referred to seems about notification, did you mean another issue? Reopening this for now, please close with the duplicate one you found. Thanks!

**Comment by jnm2377** [comment] 2019-02-09 22:49
#1004 progress indicator.

**Comment by asudoh** [comment] 2019-02-09 22:50
Thanks @jnm2377!

**Closed** 2019-02-09 22:49 UTC
Labels: v10 :new:
