### ISSUE TITLE
[Design] Component page theme/variant switcher — ready

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#357] opened 2019-09-19 16:40 UTC
As a user I want to be able to view the live demo component in the 4 different themes as well as be able to see the different variants and modifiers in one window instead of multiple.

**Comment by aagonzales** [comment] 2019-09-19 16:52
# Concepts:

### Option 1: content switcher 
![image](https://user-images.githubusercontent.com/11670886/65263917-24b05000-dad3-11e9-9ddb-5268928c3afc.png)

### Option 2: tabs & variants in list
![image](https://user-images.githubusercontent.com/11670886/65263991-4f020d80-dad3-11e9-8b41-2dee08a6cf97.png)

### Option 3: All in right panel
![image](https://user-images.githubusercontent.com/11670886/65264034-6214dd80-dad3-11e9-8cac-c321814f82c1.png)

### Option 4: theme and variant tabs at top
![image](https://user-images.githubusercontent.com/11670886/65264168-abfdc380-dad3-11e9-9407-552219bebc1c.png)

### High contrast panel
![image](https://user-images.githubusercontent.com/11670886/65264265-d94a7180-dad3-11e9-8fde-7fcef9056169.png)

### Left panel
![image](https://user-images.githubusercontent.com/11670886/65264322-f54e1300-dad3-11e9-95fb-b1688271a402.png)

**Comment by aagonzales** [comment] 2019-09-25 16:16
Here is the direction we're trending.
- Themes use a content switcher like on the color/usage page
- Theme switching is controlled at a global website level. If one component is switched to the Gray 100 theme then all component examples automatically switch to that theme as well. 
- Try to avoid dropdowns and show the options are much as possible. 
- React code is hidden but can be shown and copied. Ideally the code block content changes with what configurations are applied. 
- Link to other dev environments no longer a part of the main demo window.

![Component_Demo](https://user-images.githubusercontent.com/11670886/65619425-bad9ef80-df85-11e9-81f8-de47c6aad035.png) 
![Component_Demo-2](https://user-images.githubusercontent.com/11670886/65619449-c5948480-df85-11e9-9855-d867b243a545.png)

**Comment by aagonzales** [comment] 2019-09-25 18:14
### Possible components

![components](https://user-images.githubusercontent.com/11670886/65628129-730f9400-df96-11e9-8f45-82faba3ca72e.png)

**Comment by vpicone** [comment] 2019-09-25 19:31
Seeing the code update in real time is pretty essential towards making this usable. One of the big issues with storybook is how our code snippets aren't usable. 

I don't think having a copy button makes sense without also having the live code that you're copying displayed. I think shopify's example for this is a great model. Something like the `basic fields` example above is what I imagined (maybe without those framework links).

The show more is tough here since it'd also pull down the sidebar with all the knobs, I think it might be better just to make that area scrollable. One thing to keep in mind is that since the components are in isolation, there's going to be way lose code than as-is, so we might be able to ditch the show more.

**Comment by aagonzales** [comment] 2019-09-27 15:25
OK in order to make some decisions around the code block I need a little more insights into what users would want to do with it. Keep in mind this demo window is also for dev **and** design to showcase what's possible with the component. eventually code, usage and style will all liver harmoniously on one long page together.

**Dev needs I'm currently understanding:**
- Code update in real time with modifiers
- Users can edit code in code block
- Copy button nested with code, not alone.

**Questions (for dev):**
- Do we need to show props (like on Polaris?) What are they?
- Would it be ok to completely hide the code by default or would you want to see it up.
- Where is the primary place we want users looking at component code?
- Will/should this component demo replace the React sandbox?
- Window will only ever show react code? 
- Is the react code useful to see if you're not a react user?

**Comment by aagonzales** [comment] 2019-09-27 16:01
### Code block options - WIP

![image](https://user-images.githubusercontent.com/11670886/65783777-26eb5d80-e116-11e9-83a5-2407be475f68.png)

**Comment by jnm2377** [comment] 2019-09-27 16:21
@aagonzales These are my thoughts on your questions: 

> Do we need to show props (like on Polaris?) What are they?

Yes. This is something that needs work in our storybook, as well. We've heard time and time again from users that they don't know where to find the props. We don't really do a good job of surfacing them, and they are very essential for React, not just for different variations but also for a11y and state related props.

> Would it be ok to completely hide the code by default or would you want to see it up.

I'd want to see it up by default but having an option to hide it would be ok. 

> Where is the primary place we want users looking at component code?

I think existing React users primarily look for code in Storybook, which tbh needs a lot of work because we can do better in a lot of ways. Since we're now React-first, though, I think moving our website to be React and aiming for this to be the main place for users to find code would be ideal because we can better customize this experience than what Storybook currently offers.

> Will/should this component demo replace the React sandbox?

No. We still need sandboxes for users to reproduce bugs and stuff.

> Window will only ever show react code?

Yes. We're moving towards deprecating vanilla, and the core team will only maintain React. So my take is yes.

> Is the react code useful to see if you're not a react user?

No, it's not. But the vanilla code is not useful if you're not a vanilla user. And we're React-first now, so I think if there's any code that we should be showing it should be this.

**Comment by mjabbink** [comment] 2019-09-27 16:57
@aagonzales in the case above under Documentation I think the icons would work better on the left. or as in the right side in a column just as a visual cue that you’re leaving the site (not clickable but maybe also clickable?) Could not hurt in this case.

**Comment by joshblack** [comment] 2019-09-27 17:03
> Do we need to show props (like on Polaris?) What are they?

I think it can be helpful, being able to update the props inline and have the control change is always fun. I do think some have such a large surface area of props that it can easily make the page feel overwhelming (I'm looking at you, DataTable).

I think, because of that, keeping the demoes isolated to ideal use-cases might be preferred and then launch our or redirect to a dedicated page might be the best bang for our buck.

When it comes to what a `prop` represents, it's analogous to a symbol override in Sketch (roughly) in that you can change text, style, variant, etc.

> Would it be ok to completely hide the code by default or would you want to see it up.

I think having the code block visible at the beginning would be helpful

> Where is the primary place we want users looking at component code?

Most folks look at the storybook as they tend to give the largest amount of info

> Will/should this component demo replace the React sandbox?

I think it can replace if we fully document all the props, however this might mean having to recreate parts of storybook that folks find valuable. For context, folks often request our storybook stories for PALs/add-ons such that they can use them, as well.

> Window will only ever show react code?

I think this would be the best bet for now.

> Is the react code useful to see if you're not a react user?

Not at all 😞

**Comment by vpicone** [comment] 2019-09-27 17:58
I think being able to edit the code block isn’t super essential, but seeing the code react to changes in props before copying it is. 

I’m also on the side of showing the code by default, I don’t think there’s much to be gained from hiding it but it just adds an extra click to see the component updating every time.

**Comment by aagonzales** [comment] 2019-10-04 19:19
# Final designs for development ✅ 

**Sketch file:**
https://ibm.box.com/s/u0om4lkl4u3vm9v7j9vlfq6moarqufb4

![Component_Demo](https://user-images.githubusercontent.com/11670886/66232081-ac8a8280-e6ad-11e9-87a0-623a8c2a9302.png)

### Basic spec

![image](https://user-images.githubusercontent.com/11670886/66231641-9a5c1480-e6ac-11e9-9407-2dad7489f715.png)

### Theme Switcher
 A content switcher at the top of the window changes the theme appearance. The background of the window also changes and has a 8px white border around the edge.

![image](https://user-images.githubusercontent.com/11670886/66231729-ca0b1c80-e6ac-11e9-974b-6f2824889681.png)
![image](https://user-images.githubusercontent.com/11670886/66231803-fde64200-e6ac-11e9-8c6f-3cb060796d2d.png)

### Responsive behavior

**>large break point**
Window grows proportionally with 12 columns above large breakpoint
![image](https://user-images.githubusercontent.com/11670886/66232854-764e0280-e6af-11e9-903f-b824f350bbae.png)

**Medium and small breakpoints**
Right panel becomes collapsible/expandable and is collapsed by default. Once open panel is only collapsible by clicking the x or clicking outside of the panel.
![image](https://user-images.githubusercontent.com/11670886/66232911-9bdb0c00-e6af-11e9-8432-bab3d6be8389.png)

![image](https://user-images.githubusercontent.com/11670886/66233282-9631f600-e6b0-11e9-9728-9a0f1c65457e.png)

### Full page mode
By clicking the `maximize` arrows the component window takes over the whole page. This allows the user to have a bigger working area.
![image](https://user-images.githubusercontent.com/11670886/66233337-bc579600-e6b0-11e9-8dc7-c7880ef687f8.png)

### Example of other components 
![image](https://user-images.githubusercontent.com/11670886/66233486-1eb09680-e6b1-11e9-8d86-f8578ef4780e.png)
![image](https://user-images.githubusercontent.com/11670886/66233522-38ea7480-e6b1-11e9-8a1f-96da5b996b70.png)

**Comment by vpicone** [comment] 2019-11-01 22:39
@aagonzales could you clarify what you mean by 'state'? Is that just hover/focus type interactions or something like the contents of an input?

**Comment by aagonzales** [comment] 2019-11-04 16:04
States in this context would be something that the user can't see by interacting with the component like: disabled, skeleton, invalid. 

States that should just be viewed through interacting with the component itself (these don't need extras controls):
- enabled
- hover
- focus
- active

**Comment by vpicone** [comment] 2019-11-05 21:12
@aagonzales if you have a spec a little info icon or something next to the knobs that'd be great

![Screen Shot 2019-11-05 at 3 12 13 PM](https://user-images.githubusercontent.com/4078018/68246575-ae15d600-ffde-11e9-8162-a18933a4a728.png)

It could also be a dashed underline on the knob name or something maybe?

**Comment by jeanservaas** [comment] 2019-11-07 23:57
@vpicone mike made the point that this could be a Gatsby component potentially too right?

**Comment by mjabbink** [comment] 2019-11-08 00:59
I don’t see why not and also should be something we focus on this cycle since it has huge impact on user experience. Will also resolve some issues we currently have in Carbon when displaying a component in the demo window. But Gatsby or not we should totally rock this.

**Comment by mjabbink** [comment] 2019-11-08 23:28
What a second. Isn’t the Carbon site Gatsby theme? It’s no different to BC, IDL, Design for AI, etc. I wonder if there are some components we do not want the entire Design Ecosystem to use can they be hidden? Or is that anti open source community. I’m fine either way but then I’m think it’s a Gatsby component for sure.

**Closed** 2019-12-09 19:35 UTC
Labels: type: visual :art:

**Comment by mjabbink** [comment] 2019-12-09 20:37
Can’t wait to see this in action

**Comment by mjabbink** [comment] 2019-12-15 20:58
From what I see in above visual specs this needs adjusting so snippet goes full width under demo window and side panel
