### ISSUE TITLE
Search UX Fixes

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#596] opened 2018-12-12 17:27 UTC
Problem: Our search function is not well configured. For example, a user looking for guidance on "skeleton states" gets zero results from a search for "skeleton," even though the site contains guidance on that topic. This is only one example and points to larger underlying issues.

Audit the UX of our search experience. Considerations:

- [ ] Are search results behaving as expected/desired?
- [ ] Is there any way we could restructure our metadata to improve search performance?
- [ ] Should/can we build a full search results page?
- [ ] What is configurable in Algolia?
. . .

**Comment by alisonjoseph** [comment] 2018-12-14 02:21
possibly duplicate of https://github.com/carbon-design-system/carbon-website/issues/588 ?

**Comment by claycrenshaw** [comment] 2018-12-14 17:53
Don't think this is a duplicate. . . 588 is about search as a component in the design system, not the search on the carbon site itself.

**Closed** 2019-04-27 19:38 UTC
Labels: project: website, wontfix
