### ISSUE TITLE
[icon/pictograms page] update search/filter spec to mirror IDLs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#811] opened 2020-01-20 19:47 UTC
We need to update our search and filters on our Icon and Pictograms page to match the one that is currently on IDLs UI icons page.

IDL:
<img width="1680" alt="Screen Shot 2020-01-20 at 1 45 46 PM" src="https://user-images.githubusercontent.com/43969356/72753754-63423e00-3b8b-11ea-9eb2-5c5f6c42855b.png">
<img width="1680" alt="Screen Shot 2020-01-20 at 1 46 07 PM" src="https://user-images.githubusercontent.com/43969356/72753755-63423e00-3b8b-11ea-8fb1-8f58edd44257.png">

------------------------------------------------------------------------------------------------

Carbon:
<img width="1680" alt="Screen Shot 2020-01-20 at 1 46 35 PM" src="https://user-images.githubusercontent.com/43969356/72753775-70f7c380-3b8b-11ea-99b2-cf59df8fcc57.png">

**Comment by jnm2377** [comment] 2020-01-20 20:22
I think this is a duplicate of https://github.com/carbon-design-system/carbon-website/issues/649
Which still needs a decision about whether to remove the library or not. Currently, blocked until someone decides.

**Closed by jnm2377** 2020-01-20 20:22 UTC
Labels: type: enhancement 💡
